//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int MaBL { get; set; }
        public int MaThanhVien { get; set; }
        public string NoiDungTraLoi { get; set; }
        public Nullable<System.DateTime> NgayTraLoi { get; set; }
        public Nullable<bool> hienthi { get; set; }
    
        public virtual BinhLuan BinhLuan { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
